import { NeedRecord, VolunteerRecord } from "@/lib/types";

const now = Date.now();

export const seedNeeds: NeedRecord[] = [
  { id: "need-1", raw_input: "Ration kits needed for 40 families near Dharavi transit camp.", need_category: "food", location_description: "Dharavi, Mumbai", lat: 19.0477, lng: 72.8581, urgency_score: 4, beneficiary_count: 40, status: "open", volunteer_id: null, created_at: new Date(now - 2 * 36e5).toISOString(), ward: "Mumbai Central" },
  { id: "need-2", raw_input: "Elderly patients need insulin refill and nurse visits in Govandi.", need_category: "medical", location_description: "Govandi, Mumbai", lat: 19.0552, lng: 72.9163, urgency_score: 5, beneficiary_count: 12, status: "open", volunteer_id: null, created_at: new Date(now - 4 * 36e5).toISOString(), ward: "Mumbai East" },
  { id: "need-3", raw_input: "Temporary tarpaulin shelter requested after fire in Kurla settlement.", need_category: "shelter", location_description: "Kurla, Mumbai", lat: 19.0728, lng: 72.8826, urgency_score: 5, beneficiary_count: 25, status: "open", volunteer_id: null, created_at: new Date(now - 6 * 36e5).toISOString(), ward: "Mumbai East" },
  { id: "need-4", raw_input: "After-school tutoring support requested for municipal school children in Chembur.", need_category: "education", location_description: "Chembur, Mumbai", lat: 19.0522, lng: 72.9005, urgency_score: 2, beneficiary_count: 30, status: "open", volunteer_id: null, created_at: new Date(now - 26 * 36e5).toISOString(), ward: "Mumbai East" },
  { id: "need-5", raw_input: "Women support circle and counseling needed near BKC migrant hostel.", need_category: "mental_health", location_description: "Bandra Kurla Complex, Mumbai", lat: 19.0607, lng: 72.8697, urgency_score: 3, beneficiary_count: 18, status: "assigned", volunteer_id: "vol-5", created_at: new Date(now - 10 * 36e5).toISOString(), ward: "Mumbai North" },
  { id: "need-6", raw_input: "Broken community toilet pipeline causing overflow in Seelampur lane 4.", need_category: "infrastructure", location_description: "Seelampur, Delhi", lat: 28.6692, lng: 77.269, urgency_score: 4, beneficiary_count: 80, status: "open", volunteer_id: null, created_at: new Date(now - 7 * 36e5).toISOString(), ward: "North East Delhi" },
  { id: "need-7", raw_input: "Need cooked meals for migrant workers near Anand Vihar bus depot.", need_category: "food", location_description: "Anand Vihar, Delhi", lat: 28.6469, lng: 77.3151, urgency_score: 4, beneficiary_count: 55, status: "open", volunteer_id: null, created_at: new Date(now - 5 * 36e5).toISOString(), ward: "East Delhi" },
  { id: "need-8", raw_input: "Mobile health camp requested for construction workers in Okhla phase 2.", need_category: "medical", location_description: "Okhla Phase 2, Delhi", lat: 28.5307, lng: 77.2757, urgency_score: 3, beneficiary_count: 45, status: "open", volunteer_id: null, created_at: new Date(now - 16 * 36e5).toISOString(), ward: "South East Delhi" },
  { id: "need-9", raw_input: "Flooded rooms need dry bedding and safe overnight stay in Sangam Vihar.", need_category: "shelter", location_description: "Sangam Vihar, Delhi", lat: 28.5075, lng: 77.231, urgency_score: 5, beneficiary_count: 20, status: "open", volunteer_id: null, created_at: new Date(now - 3 * 36e5).toISOString(), ward: "South Delhi" },
  { id: "need-10", raw_input: "Volunteer teachers needed for girls' digital literacy class in Jahangirpuri.", need_category: "education", location_description: "Jahangirpuri, Delhi", lat: 28.7265, lng: 77.1624, urgency_score: 2, beneficiary_count: 35, status: "resolved", volunteer_id: "vol-4", created_at: new Date(now - 30 * 36e5).toISOString(), ward: "North West Delhi" },
  { id: "need-11", raw_input: "Counseling follow-up requested after eviction notices in Shivaji Nagar.", need_category: "mental_health", location_description: "Shivaji Nagar, Bengaluru", lat: 12.9982, lng: 77.6201, urgency_score: 4, beneficiary_count: 22, status: "open", volunteer_id: null, created_at: new Date(now - 9 * 36e5).toISOString(), ward: "Bengaluru Central" },
  { id: "need-12", raw_input: "Water tanker scheduling support needed for low-income blocks in KR Puram.", need_category: "infrastructure", location_description: "KR Puram, Bengaluru", lat: 13.0071, lng: 77.6953, urgency_score: 3, beneficiary_count: 65, status: "open", volunteer_id: null, created_at: new Date(now - 22 * 36e5).toISOString(), ward: "Bengaluru East" },
  { id: "need-13", raw_input: "Community kitchen ingredients needed near Yeshwanthpur railway colony.", need_category: "food", location_description: "Yeshwanthpur, Bengaluru", lat: 13.0285, lng: 77.5443, urgency_score: 3, beneficiary_count: 50, status: "assigned", volunteer_id: "vol-2", created_at: new Date(now - 11 * 36e5).toISOString(), ward: "Bengaluru North" },
  { id: "need-14", raw_input: "First aid volunteers required for heat exhaustion cases in Ejipura.", need_category: "medical", location_description: "Ejipura, Bengaluru", lat: 12.9457, lng: 77.6262, urgency_score: 5, beneficiary_count: 16, status: "open", volunteer_id: null, created_at: new Date(now - 90 * 6e4).toISOString(), ward: "Bengaluru South" },
  { id: "need-15", raw_input: "Repair team needed for unsafe anganwadi roof in Tannery Road.", need_category: "infrastructure", location_description: "Tannery Road, Bengaluru", lat: 12.9918, lng: 77.6173, urgency_score: 4, beneficiary_count: 28, status: "open", volunteer_id: null, created_at: new Date(now - 13 * 36e5).toISOString(), ward: "Bengaluru Central" }
];

export const seedVolunteers: VolunteerRecord[] = [
  { id: "vol-1", name: "Asha Nair", phone: "+919820000001", whatsapp: "+919820000001", skills: ["medical", "general"], availability: "both", lat: 19.076, lng: 72.8777, task_count_this_week: 1, created_at: new Date(now - 15 * 864e5).toISOString() },
  { id: "vol-2", name: "Rohan Shah", phone: "+919820000002", whatsapp: "+919820000002", skills: ["cooking", "logistics"], availability: "weekends", lat: 13.0358, lng: 77.597, task_count_this_week: 2, created_at: new Date(now - 10 * 864e5).toISOString() },
  { id: "vol-3", name: "Meera Kulkarni", phone: "+919820000003", whatsapp: "+919820000003", skills: ["construction", "general"], availability: "both", lat: 12.9716, lng: 77.5946, task_count_this_week: 1, created_at: new Date(now - 8 * 864e5).toISOString() },
  { id: "vol-4", name: "Imran Khan", phone: "+919820000004", whatsapp: "+919820000004", skills: ["teaching", "general"], availability: "weekdays", lat: 28.7041, lng: 77.1025, task_count_this_week: 3, created_at: new Date(now - 30 * 864e5).toISOString() },
  { id: "vol-5", name: "Farah Ali", phone: "+919820000005", whatsapp: "+919820000005", skills: ["counseling", "general"], availability: "both", lat: 19.0896, lng: 72.8656, task_count_this_week: 1, created_at: new Date(now - 12 * 864e5).toISOString() },
  { id: "vol-6", name: "Sandeep Verma", phone: "+919820000006", whatsapp: "+919820000006", skills: ["logistics", "cooking"], availability: "weekends", lat: 28.6139, lng: 77.209, task_count_this_week: 0, created_at: new Date(now - 18 * 864e5).toISOString() },
  { id: "vol-7", name: "Nikita Rao", phone: "+919820000007", whatsapp: "+919820000007", skills: ["medical"], availability: "both", lat: 12.9279, lng: 77.6271, task_count_this_week: 0, created_at: new Date(now - 5 * 864e5).toISOString() },
  { id: "vol-8", name: "Rahul Gupta", phone: "+919820000008", whatsapp: "+919820000008", skills: ["construction", "logistics"], availability: "weekdays", lat: 28.5355, lng: 77.391, task_count_this_week: 1, created_at: new Date(now - 7 * 864e5).toISOString() },
  { id: "vol-9", name: "Sneha Iyer", phone: "+919820000009", whatsapp: "+919820000009", skills: ["teaching", "counseling"], availability: "both", lat: 19.033, lng: 72.8407, task_count_this_week: 2, created_at: new Date(now - 20 * 864e5).toISOString() },
  { id: "vol-10", name: "Joseph D'Souza", phone: "+919820000010", whatsapp: "+919820000010", skills: ["general"], availability: "both", lat: 13.0196, lng: 77.6412, task_count_this_week: 0, created_at: new Date(now - 3 * 864e5).toISOString() }
];
